### ISSUE TITLE
hi brother, your TWRP of Redmi 8A will invalidate the touch screen of your phone after startup.

### ISSUE THREAD

**Issue by Tmalll** [redmi8a/android_device_xiaomi_olivelite#1]
hi brother, your TWRP of Redmi 8A will invalidate the touch screen of your phone after startup.
How can I solve this problem?

**Comment by milankragujevic** [comment]
Is this 3GB RAM variant?

**Comment by Tmalll** [comment]
> Is this 3GB RAM variant?

不，我的手机是4g内存+64g存储的
No, my phone has 4g memory and 64g storage。
![IMG_20200108_102427](https://user-images.githubusercontent.com/40192806/71945293-60496400-3201-11ea-8800-ad235797ae8d.jpg)

![IMG_20200108_102421](https://user-images.githubusercontent.com/40192806/71945310-6fc8ad00-3201-11ea-853d-c421e5ef65cf.jpg)

**Comment by milankragujevic** [comment]
That is not supported, I only have tested 2/32 GB version. 

I got report that TWRP does not work on 3/64GB, and now I see on 4/64GB too it does not work.

I can not help you. I no longer use this phone.

**Comment by Ornolfr** [comment]
@milankragujevic It does not work on 2/32 GB version either.

**Comment by milankragujevic** [comment]
It does on EU model, revision from end of 2019.
